-- =============================================================================
-- mind_memory — per-Mind persistent memory layer (Feature 3.5)
-- =============================================================================
-- Salient facts and observations the synthesis agent reads from + writes to
-- over time. Three kinds:
--   - fact:           a specific proposition the agent extracted
--   - essay_summary:  a brief gist of an essay generated by the agent
--   - observation:    a noticing / pattern the agent flagged
--
-- Embedding column is nullable for now — populated later by a background pass.
-- source_essay_id is text rather than a foreign key because the essays table
-- doesn't exist yet (Feature 3 ships it).
--
-- Apply in Supabase SQL editor.
-- =============================================================================

create extension if not exists vector;

create table if not exists public.mind_memory (
  id uuid primary key default gen_random_uuid(),
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  kind text not null check (kind in ('fact', 'essay_summary', 'observation')),
  content text not null check (char_length(trim(content)) > 0),
  embedding vector(768),
  source_node_id uuid references public.nodes(id) on delete set null,
  source_essay_id text,
  created_by uuid references public.users(id) on delete set null,
  weight float not null default 1.0,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  expires_at timestamptz
);

create index if not exists mind_memory_workspace_created_at_idx
  on public.mind_memory(workspace_id, created_at desc);

create index if not exists mind_memory_workspace_kind_idx
  on public.mind_memory(workspace_id, kind);

-- updated_at trigger
drop trigger if exists set_mind_memory_updated_at on public.mind_memory;
create trigger set_mind_memory_updated_at
before update on public.mind_memory
for each row execute function private.set_updated_at();

-- RLS — workspace members can read; writes from the server-side service role.
alter table public.mind_memory enable row level security;

drop policy if exists "Workspace members can read mind memory" on public.mind_memory;
create policy "Workspace members can read mind memory"
on public.mind_memory for select
to authenticated
using (private.is_workspace_member(workspace_id));

-- Writes are intentionally NOT exposed via RLS — the server uses the service
-- role to insert/update/delete. This keeps memory writes deliberate and
-- auditable; the client can never write directly.

-- =============================================================================
-- ROLLBACK
-- =============================================================================
-- drop table if exists public.mind_memory;
