// One-off: retag essay row(s) whose UUID starts with a given prefix so
// trail.kind = 'digest'. Use when an essay was generated by the digest
// cron before the kind tag was introduced, and should display as a
// Weekly Digest in the Insights list.
//
// Usage:
//   node scripts/retag-digest.mjs <id-prefix>
// Example:
//   node scripts/retag-digest.mjs da4e35fb

import { readFileSync } from 'node:fs';
import { createClient } from '@supabase/supabase-js';

const prefix = process.argv[2];
if (!prefix || prefix.length < 6) {
  console.error('usage: node scripts/retag-digest.mjs <id-prefix>  (>=6 chars)');
  process.exit(1);
}

// Load .env.local without bringing in extra deps.
const env = Object.fromEntries(
  readFileSync('.env.local', 'utf8')
    .split('\n')
    .filter((l) => l && !l.startsWith('#') && l.includes('='))
    .map((l) => {
      const i = l.indexOf('=');
      return [l.slice(0, i).trim(), l.slice(i + 1).trim()];
    }),
);

const url = env.NEXT_PUBLIC_SUPABASE_URL;
const key = env.SUPABASE_SERVICE_ROLE_KEY;
if (!url || !key) {
  console.error('Missing SUPABASE_URL or SERVICE_ROLE_KEY in .env.local');
  process.exit(1);
}

const supa = createClient(url, key, { auth: { persistSession: false } });

// PostgREST can't LIKE a uuid column directly; fetch and filter in JS.
const { data: all, error: findErr } = await supa
  .from('essays')
  .select('id, title, trail, created_at')
  .order('created_at', { ascending: false });

if (findErr) {
  console.error('lookup failed:', findErr.message);
  process.exit(1);
}
const matches = (all ?? []).filter((r) => r.id.startsWith(prefix));
if (matches.length === 0) {
  console.error(`no essay with id prefix '${prefix}'`);
  process.exit(1);
}
if (matches.length > 1) {
  console.error(`ambiguous: ${matches.length} essays match prefix '${prefix}'`);
  for (const r of matches) console.error(`  ${r.id}  ${r.title ?? '(no title)'}`);
  process.exit(1);
}

const row = matches[0];
const nextTrail = { ...(row.trail ?? {}), kind: 'digest' };
const { error: updErr } = await supa
  .from('essays')
  .update({ trail: nextTrail })
  .eq('id', row.id);

if (updErr) {
  console.error('update failed:', updErr.message);
  process.exit(1);
}

console.log(`retagged ${row.id} → trail.kind='digest'`);
console.log(`  title: ${row.title ?? '(none)'}`);
console.log(`  prev trail.kind: ${row.trail?.kind ?? '(unset)'}`);
