'use client';
import { useEffect, useState } from 'react'; import { getAccessToken, supabaseBrowser } from '@/lib/client-auth';
type Workspace={role:string;workspaces:{id:string;name:string;created_at:string}}; type Tag={id:string;shift_name:string;description:string|null};
export default function Dashboard(){const [workspaces,setWorkspaces]=useState<Workspace[]>([]);const [workspaceId,setWorkspaceId]=useState('');const [captureUrl,setCaptureUrl]=useState('');const [captureText,setCaptureText]=useState('');const [tags,setTags]=useState<Tag[]>([]);
const authedFetch=async(url:string,init?:RequestInit)=>{const token=await getAccessToken();return fetch(url,{...init,headers:{'Content-Type':'application/json',authorization:`Bearer ${token}`,...(init?.headers??{})}})};
const loadWorkspaces=async()=>{const r=await authedFetch('/api/workspaces');const d=await r.json();setWorkspaces(d.workspaces??[]);if(!workspaceId&&d.workspaces?.[0]?.workspaces?.id)setWorkspaceId(d.workspaces[0].workspaces.id)};
const createWorkspace=async()=>{const name=prompt('Workspace name?');if(!name)return;await authedFetch('/api/workspaces',{method:'POST',body:JSON.stringify({name})});await loadWorkspaces();};
const capture=async()=>{await authedFetch('/api/capture',{method:'POST',body:JSON.stringify({workspaceId,url:captureUrl||undefined,rawText:captureText||undefined})});setCaptureUrl('');setCaptureText('');alert('Captured');};
const loadTags=async()=>{if(!workspaceId)return;const r=await authedFetch(`/api/tags?workspaceId=${workspaceId}`);const d=await r.json();setTags(d.tags??[])};
const addTag=async()=>{const shiftName=prompt('Tag name');if(!shiftName)return;const description=prompt('Description')??'';await authedFetch('/api/tags',{method:'POST',body:JSON.stringify({workspaceId,shiftName,description})});await loadTags();};
useEffect(()=>{supabaseBrowser.auth.getSession().then(loadWorkspaces);},[]); useEffect(()=>{loadTags();},[workspaceId]);
return <main><h1>Dashboard</h1><div style={{display:'flex',gap:8}}><button onClick={createWorkspace}>New Workspace</button><select value={workspaceId} onChange={(e)=>setWorkspaceId(e.target.value)}><option value=''>Select workspace</option>{workspaces.map(w=><option key={w.workspaces.id} value={w.workspaces.id}>{w.workspaces.name} ({w.role})</option>)}</select></div><h2>Capture</h2><div style={{display:'grid',gap:8,maxWidth:760}}><input placeholder='https://...' value={captureUrl} onChange={(e)=>setCaptureUrl(e.target.value)}/><textarea placeholder='Optional notes' value={captureText} onChange={(e)=>setCaptureText(e.target.value)}/><button onClick={capture}>Capture Signal</button></div><h2>Framework Tags</h2><button onClick={addTag}>Add Tag</button><ul>{tags.map(t=><li key={t.id}><strong>{t.shift_name}</strong> — {t.description}</li>)}</ul></main>}
